### ISSUE TITLE
How much energy does the Libra sensor draw?

### ISSUE THREAD

**Issue by acollien** [JoernL/LimiTTer#12]
There's a little battery (silver or something?) in the sensor - or so I read - which allows it to run for 8 hours and collect data. It gets charged via the NFC process with a phone or the reader (I assume).

So, I figure, for you to make this project work, you'd need to know the minimum energy the sensors need to run, right? or the amount required to charge the sensor's little internal battery? 
I'm guessing it's minuscule - a percentage of a fraction of a watt?

**Comment by SandraK82** [comment]
The battery is not charged through the nfc readout. In fact I can now confirm that the battery expires at some point, rendering the tag useless as the reading of the tag is then not reliable possible. Some of my first analyzed tags dating back to February/march 2016 are now dead. 

Von meinem iPhone gesendet
