### ISSUE TITLE
Hardware Component List - Canada

### ISSUE THREAD

**Issue by apabari** [JoernL/LimiTTer#22]
Hello,

I'm in Canada and just pre-ordered the Freestyle Libre.  (I'm currently using a Dexcom G4 and an xDrip, with the xDrip+ app, but eager to try out the Libre and LimiTTer.)

Was hoping to get some guidance on some of the components -- as I'm not sure where to get this items:
- USB to TTL Serial Adapter Module
- Lipo battery 3.7V 100mAh 28x12x5mm

I can see most of the others are available on www.robotshop.com/ca.

Could anyone please post a link to where these two items available for purchase?  Just want to ensure I get the right components.

Thanks,
Andy

**Comment by keencave** [comment]
I would suggest to look on Aliexpress - there you will find: https://de.aliexpress.com/item/Free-shipping-1pcs-FT232RL-FT232-FTDI-USB-3-3V-5-5V-to-TTL-Serial-Adapter-Module/32460118879.html?spm=a2g0x.search0104.3.7.j9PYkg&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10065_10151_10068_10193_10194_10304_10307_10137_10060_10302_10155_10154_10056_10055_10054_10059_100031_10099_10103_10102_10052_10053_10142_10107_10050_10051_10320_10321_10322_10326_10084_10083_10080_10082_10081_10177_10110_10111_10112_10113_10114_10180_10312_10313_10184_10314_10315_10316_10319_10078_10079_10073_10186-10050,searchweb201603_17,ppcSwitch_4&btsid=f2024a6a-3c47-45fe-8698-6a6f34b31a6b&algo_expid=1da2e6b0-e177-42e5-9eaa-16fbc435a8c7-0&algo_pvid=1da2e6b0-e177-42e5-9eaa-16fbc435a8c7 and a lot of LiPo batteries which all should fit.

**Comment by apabari** [comment]
Thanks
